### ISSUE TITLE
move outgoing SMS code to PSTN process

### ISSUE THREAD

**Issue by mndrix** [AGWA/sms-over-xmpp#15]
[This code](https://github.com/mndrix/sms-over-xmpp/blob/44eae965cdf72c1310dd5228e2ab2ef76096404b/gateway.go#L140-L160) uses the telephony provider to send an outgoing SMS.  Because it's an interaction with the phone network, it belongs in the PSTN process not the Gateway process.

**Comment by AGWA** [comment]
N/A in new architecture.
