### ISSUE TITLE
prepare read receipts in main gateway loop

### ISSUE THREAD

**Issue by mndrix** [AGWA/sms-over-xmpp#16]
Before we can fix #15 we have to move [this code](https://github.com/mndrix/sms-over-xmpp/blob/44eae965cdf72c1310dd5228e2ab2ef76096404b/gateway.go#L162-L181) to the main gateway loop.  `sms2xmpp` should prepare as much of the receipt as possible and store it based on the XMPP stanza ID.  The gateway loop should receive a channel message saying "XMPP message 1234 was successfully sent as SMS 9876".  It can look up the receipt for XMPP stanza 1234 then associate it with SMS 9876.  When the delivery status update arrives for that SMS, everything will be ready.

**Comment by AGWA** [comment]
N/A in new architecture.
