### ISSUE TITLE
component should own XMPP users/rosters data

### ISSUE THREAD

**Issue by mndrix** [AGWA/sms-over-xmpp#19]
When the XMPP process crashes, it loses all roster data (subscriptions, names, etc).  That's because the data is [owned by that process](https://github.com/mndrix/sms-over-xmpp/blob/53077fce1e861664b872ba85d35da78ab6885d54/xmpp.go#L35).  Most of this data is recreated as needed, so it's only a minor annoyance.  To avoid the annoyance, the data should persist beyond the life of the XMPP process.

The easiest solution is to move ownership of the data structure from the XMPP process to the component process.  This is similar to how we handle [XMPP delivery receipts](https://github.com/mndrix/sms-over-xmpp/blob/53077fce1e861664b872ba85d35da78ab6885d54/component.go#L21-L28).  The component creates the data structure and passes it to each newly created XMPP process.

Changing ownership doesn't change the semantics or consumption of this data.  It only changes its lifetime.  Centralizing all persistent data in the component also makes way for storing this data on disk in between server restarts.

**Comment by AGWA** [comment]
N/A in new architecture.
