### ISSUE TITLE
Openfire Integration

### ISSUE THREAD

**Issue by drseussofporn** [AGWA/sms-over-xmpp#24]
This is more of an experience question than an issue. Has anyone had any luck using this with Openfire? Everything works fine with Twilio up to the point where sms-over-xmpp sends the message to Openfire; nothing happens at that juncture. I'm curious if I'm missing a step configuring the external component or if Openfire is naturally this frustrating.

**Comment by mndrix** [comment]
Sorry that I can't be more help.  I never tried it with Openfire.  I'll leave this issue open in case others can provide some guidance.  Please update here if you find a solution.

**Comment by drseussofporn** [comment]
@mndrix Thanks. If anyone else finds this issue and is interested in XMPP-SMS integration with Twilio, I actually created a Python solution that is working pretty well. If there is interest expressed (probably only if you use Openfire as sms-over-xmpp should work great for other servers) I will throw it up on GitHub. Thanks again @mndrix for laying the groundwork; there was no way I could have tackled this without your project.
