### ISSUE TITLE
Cannot find executable

### ISSUE THREAD

**Issue by gnusupport** [AGWA/sms-over-xmpp#28]
After doing `go get github.com/AGWA/sms-over-xmpp/` I cannot find executable to run. There is just sms-over-xmpp.a

Help me, as this module seems to be excellent for Prosody SMS.

**Comment by AGWA** [comment]
You need to include `...` at the end:

```
go get github.com/AGWA/sms-over-xmpp/...
```

This will install an executable named `sms-over-xmpp`.

**Comment by 717g301github** [comment]
Yes, that works. Thanks.

Do you think that external component will be found simply without providing to prosody any information but what have been specified here:  https://prosody.im/doc/components#adding_an_external_component

Which password to specify in that section for prosody? It is not logical yet.

**Comment by AGWA** [comment]
You can pick a random password for that.  It needs to match the XMPP secret that you put in the sms-over-xmpp config file,

**Comment by 717g301github** [comment]
Does Prosody finds external component over network connection?

**Comment by AGWA** [comment]
Prosody doesn't find the external component.  Instead, it's sms-over-xmpp which connects to your Prosody server over the network using the host/port/name/secret specified in the sms-over-xmpp config file.  It's similar to how a normal XMPP client connects to Prosody.

**Comment by 717g301github** [comment]
Oh, now I understand. I will set it up, it would be excellent if it works.

**Comment by 717g301github** [comment]
Thanks. How is shared secret defined in prosody?

**Comment by 717g301github** [comment]
[xmpp]
host = "127.0.0.1"
port = 5347
name = "sms.example.com"
secret = "shared secret from your XMPP server config"

Does name refer to host name? It looks logical, but I am asking because the IP address is also provided.

And shared secret is defined how?

**Comment by 717g301github** [comment]
Can it send and receive? 

Maybe that README is not enough for me.

**Comment by AGWA** [comment]
I suggest also reading the comments in the [sample config file](https://github.com/AGWA/sms-over-xmpp/blob/master/doc/sample-config.toml).

Currently, both the README and the sample config assume some knowledge of how XMPP components work.  If you read up on XMPP components, the sms-over-xmpp documentation will probably make more sense.
