### ISSUE TITLE
Nexmo Support

### ISSUE THREAD

**Issue by danielbmay** [AGWA/sms-over-xmpp#30]
Would it be possible to add Nexmo support?  I'd be willing to help (or even do the whole thing) if you point me in the right direction, although I don't have any experience with golang.  Nexmo has a (supported) start on a Go client implementation of the Nexmo APIs: https://github.com/nexmo-community/nexmo-go .

**Comment by AGWA** [comment]
Hi @danielbmay, I'm nearing completion of a rewrite of sms-over-xmpp that is simpler and more flexible for adding additional SMS providers.  I've added Nexmo support to it, and it's ready for testing.  To install it, run:

`go get src.agwa.name/sms-over-xmpp/...`

To configure it, create a configuration directory as documented at https://github.com/AGWA/sms-over-xmpp/blob/rewrite/doc/configuration.md

To run sms-over-xmpp with your configuration directory:

`$GOPATH/bin/sms-over-xmpp /path/to/config/directory`

Let me know if any of the configuration instructions are unclear or if you run into any issues with this.

**Comment by danielbmay** [comment]
Wow, that’s great!  I installed and configured it, and ran into a few errors (I had the wrong XMPP port, for example), but I think I got it running…  I did run into an error though.  I’ve attached my terminal output below:

/root/go/bin/sms-over-xmpp /etc/sms-over-xmpp
2019/08/20 12:29:58.913628 |> <stream:stream xmlns="jabber:component:accept" xmlns:stream="http://etherx.jabber.org/streams" to="itmeristem.com">
2019/08/20 12:29:58.915711 <| <?xml version='1.0'?><stream:stream id='e508ba5f-de59-41f0-8550-44181b7d03cc' xmlns:stream='http://etherx.jabber.org/streams' from='itmeristem.com' xml:lang='en' xmlns='jabber:client'><stream:features><starttls xmlns='urn:ietf:params:xml:ns:xmpp-tls'><required/></starttls></stream:features>
2019/08/20 12:29:58.916194 |> <handshake>5a87ccbecc2ab596babc473a0973e7ecf6e7fde7</handshake>
2019/08/20 12:29:58.916398 <| <stream:error><unsupported-stanza-type xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error></stream:stream>
2019/08/20 12:29:58.916498 <| : EOF
2019/08/20 12:29:58 Error receiving from server: EOF

Thanks,
Dan

**Comment by AGWA** [comment]
Hi @danielbmay - based on the output, it looks like you're connecting to the client port of your XMPP server rather than the component port.  I'll update the docs to make it clear you need to use the component port.

There isn't a standard port number for XMPP components.  If you're not sure what port number your server uses, you might need to configure it.  For Prosody, see the section "Adding an external component" here: https://prosody.im/doc/components
