### ISSUE TITLE
Add auto +1 to number based on config

### ISSUE THREAD

**Issue by ioscanner** [AGWA/sms-over-xmpp#32]
As we discussed.  Add config option to add +1 to the number on outbound SMS messages.  Could just have an option that says plus1=yes # require +1 to be added before sending.  So if they add a 1 just add the +.  I +1 is already present send it on.  I think this would be the cleanest.  Since some carriers don't require.

**Comment by AGWA** [comment]
I'm going to add a `default_prefix` config option to specify a prefix that is automatically added to phone numbers that don't already start with `+`. That way people in other countries can specify their own national prefix.

**Comment by ioscanner** [comment]
Perfect that is a great solution.

**Comment by ioscanner** [comment]
I tried to add default_prefix +1 to the config and test with just areacode and number.  But it doesn't seem to add the +1 to the number.

**Comment by AGWA** [comment]
I just pushed an update with `default_prefix` support.  Please give it a try and let me know how it works.
