### ISSUE TITLE
Ability to send message to xmpp group

### ISSUE THREAD

**Issue by ioscanner** [AGWA/sms-over-xmpp#33]
I did a test trying to setup a group and wanted to route the inbound SMS to that group.  Have you been able to do this?  Would be nice to allow a group to monitor a single room to respond to texts so everyone can see the response.  I guess that could get messy.  if it send all responses out.   Guess they can use single group to acknowledge they responded.  If a message is sent to many users.

**Comment by AGWA** [comment]
By "group" do you mean a multi-user-chat/conference room?  I have not tried that.  I wouldn't expect it to work without a lot of effort.

The easiest way to accomplish what you want is probably to create a dedicated XMPP account for the phone number, have everyone log in to that account, and use message carbons so all clients see the response.  It's not the prettiest solution but it works.

**Comment by ioscanner** [comment]
True, muc makes a mess of it.  Just a thought.  I did test it was not happy.  LOL
