### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by sowegatel** [AGWA/sms-over-xmpp#34]
Would be really nice to have support for https with the ability to provide certificates. I'm thinking of using this as solution for some clients in the medical field.

**Comment by sowegatel** [comment]
I've found where to play with it in main.go. I think I've got it almost figured out. I'm getting a certificate authority unknown when trying to do it with letsencrypt cert.

**Comment by sowegatel** [comment]
I've got it working statically with letsencrypt certs. I've got to figure out how to toggle this in the configuration file to allow for certificate and key entry if https is enabled.

**Comment by ioscanner** [comment]
What did you do to get letsencrypt working?

**Comment by sowegatel** [comment]
The only change I made was this.
        go func() {
                log.Fatal(httpServer.ListenAndServeTLS("/etc/sms-over-xmpp/fullchain.pem","/etc/sms-over-xmpp/privkey.pem"))
        }()

        log.Fatal(service.RunXMPPComponent())
}

**Comment by sowegatel** [comment]
In /cmd/sms-over-xmpp/main.go

**Comment by AGWA** [comment]
HTTPS is now supported by sms-over-xmpp using the new `-listen` flag.

Examples:

* `-listen tls:/path/to/certificate.pem:tcp:8443` to listen on TCP port 8443 with an HTTPS certificate in `/path/to/certificate.pem`. This file must be a single PEM file containing the private key, the certificate, and the intermediate certificate chain (you can create such a file by concatenating `privkey.pem` and `fullchain.pem`).

* `-listen tls:sms.example.com:tcp:443` to listen on TCP port 443 with an automatically-obtained HTTPS certificate for sms.example.com.  sms-over-xmpp must be be publicly-accessible on port 443 for this to work.
