### ISSUE TITLE
using two different accounts to one provider

### ISSUE THREAD

**Issue by ioscanner** [AGWA/sms-over-xmpp#35]
I have two different domains on my server.  Both routing SMS thru signalwire.  It seems I can setup provider signalwire and it works to one domain.  But when I try to create a second provider to signalwire to handle routing their calls thru their API tokens it doesn't work.

Is this not possible with the current design.  I tried to change the file names to different names, but it seems it is linked to the "type" name.

Is their a way to get this to work?

Thank you!

**Comment by AGWA** [comment]
This is supported - just create two files in the `providers` directory with different names, and put `type signalwire` in each one.  If this doesn't work, let me know in detail what goes wrong.

**Comment by ioscanner** [comment]
That is how I tried to configure it.  But when I do I just get when I try to send and inbound message.

2019/10/14 14:42:54.684228 |>

Is there a way to get more debug info?

**Comment by ioscanner** [comment]
That is how I have it configured.  It works with just one provider.  Now I think I see what might be the issue.  Both providers are the same provider.  But have different tokens as they are in different sub accounts.  So the webhook will have signalwire (user twice) and two different passwords.  I think the username should use the provider file name so if I have company1 and company2 both using signalwire they need to be able to route calls in and out based on their tokens.

**Comment by AGWA** [comment]
The username is completely ignored.  The routing is done exclusively by the path component before `/message`. As long as that matches the provider filename it should work.

**Comment by ioscanner** [comment]
So which username and password will be the default for the webook if you have two different files.  Or do it just check both files for a password match.

**Comment by AGWA** [comment]
The password needs to match the `http_password` in the provider file specified by the path component right before `/message`

**Comment by ioscanner** [comment]
Ah ok.  So the username is just there as a placeholder.

Thanks
