### ISSUE TITLE
422 issue from signalwire

### ISSUE THREAD

**Issue by ioscanner** [AGWA/sms-over-xmpp#36]
When sending sms from signalwire to sms-over-xmpp I get:

2019/10/21 15:04:46.911791 |> <message from="+1number@sms.domain.com" to="user@domain.com/client" type="error"><body>Sending SMS failed: HTTP error from Twilio: 422 Unprocessable Entity</body></message>

The message is still delivered, but still throws an error.

**Comment by AGWA** [comment]
Based on that error message, you're using an old version of sms-over-xmpp. Please upgrade to the latest version, which should fix the problem.
