### ISSUE TITLE
Latest code docs

### ISSUE THREAD

**Issue by ioscanner** [AGWA/sms-over-xmpp#37]
It looks like the latest code on github the documentation doesn't match.  The config file now wants "=" instead of a space.  But has an error of after it reads the config file:

panic: Couldn't choose an SMS provider: Need to configure an SMS provider

I do have the config directory with the provider  and user files as before.  I tried to use the "=" separator but that didn't seem to work.

**Comment by ioscanner** [comment]
It looks like all the confg info is now in the single config file.  But now it only takes a single provider entry for "signalwire".  I have two different API and tokens based on two different domains.  This was possible with the old config.  How can this be done with the new configuration file?

**Comment by AGWA** [comment]
You're looking at the old code and docs.  Make sure to use the `rewrite` branch.

**Comment by ioscanner** [comment]
Ah that is what happened.  It pulled the old code and not the new code.

Thanks

**Comment by AGWA** [comment]
If you're installing with `go get`, use this import URL:

`go get src.agwa.name/sms-over-xmpp/...`

That will pull the rewrite branch.
