### ISSUE TITLE
keep alive

### ISSUE THREAD

**Issue by mndrix** [AGWA/sms-over-xmpp#4]
Prosody disconnects an external component if it doesn't communicate after 6 hours.  Implement [XEP-0199](http://xmpp.org/extensions/xep-0199.html) and send ping requests to the server (if it supports them) every so often (configurable duration with reasonable default) to keep the connection alive.  We might as well respond to ping requests too, while we're at it.

Need to implement #3 first.

**Comment by mndrix** [comment]
I just realized that implementing #3 will slightly reduce the need for this issue.  Clients routinely send service discovery requests to the component.  Right now we don't respond.  Once service discovery is implemented, we'll automatically respond to those requests which will keep the connection alive for a while.  One more reason to start with #3 first.

**Comment by AGWA** [comment]
This should be fixed by the new XMPP library sending whitespace pings.
