### ISSUE TITLE
mod_remote_roster fix

### ISSUE THREAD

**Issue by mwild1** [AGWA/sms-over-xmpp#46]
Hi! I'm a Prosody developer, and just stumbled across this project.

I noticed in the README that you say you sent a patch to mod_remote_roster. Unfortunately it looks like that was caught in a spam filter and never made it to the mailing list. I therefore don't have the original patch you sent, but I have fixed the issue I believe it fixed [in this commit](https://hg.prosody.im/prosody-modules/rev/ad6e9b0fd15b).

**Comment by AGWA** [comment]
Thank you @mwild1! I can confirm that your commit fixes the bug.
